// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'batchopen-menu-open-browser'
  | 'batchopen-menu-open-browser-missing-pdf'
  | 'batchopen-menu-reconcile-attachments'
  | 'batchopen-menu-save-via-connector'
  | 'batchopen-menu-search-scholar'
  | 'batchopen-menu-search-web'
  | 'batchopen-submenu';
