// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "fallback": string;
      "searchTemplate": string;
      "confirmAbove": number;
      "delayMs": number;
      "reconcileWindowMinutes": number;
      "reconcileSavedItems": boolean;
      "attachmentWaitMs": number;
    };
  }
}
